### ISSUE TITLE
Problem with the sign up modal

### ISSUE THREAD

**Issue by AdrianFoo97** [B1601563/Jinjang-Empowerment-Ebusiness#4]
I think that the sign-up modal is too long that the user needs to scroll down and too many forms to fill in for the company. This defeat the purpose of using modal.

**Comment by AdrianFoo97** [comment]
For the database, I think we need add userType to the user table.

**Comment by B1601563** [comment]
Yes, I realized the scrolling problem too while testing. That's why I included userType as a hidden input in index.php to determine whether the user is a Client or Job Seeker.
